baseurl = "https://blog.donkeysharp.xyz"
languageCode = "en"
title = "Sergio Guillen"
theme = "beautifulhugo"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
enableEmoji = true
pluralizelisttitles = false
googleAnalytics = "UA-112385104-1"
canonifyurls = true

paginate = 5

[languages]
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
  [languages.en]
    contentDir = "content/en"
    languageName = "English"

[Params]
  navbarTitle  = "DONKEYSHARP"
  subtitle = ":() { :|:& }; :"
  displayTitleOnHeading = true
  logo = "img/donkeysharp.png"
  commit = false
  rss = true
  comments = true
  homeTitle = "My Blog"
  readingTime = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  languageIcon = "img/flags/en.png"
[languages.es.params]
  homeTitle = "Mi Blog"
  languageIcon = "img/flags/es.png"

[Author]
  name = "Sergio Guillen"
  github = "donkeysharp"
  twitter = "donkeysharp"
  instagram = "donkeysharp"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1
[[languages.es.menu.main]]
  name   = "Blog"
  url    = ""
  weight = 1

[[menu.main]]
  name = "About me"
  url = "about/"
  weight = 2
[[languages.es.menu.main]]
  name   = "Sobre mí"
  url    = "about/"
  weight = 2


# This makes links to open in another tab
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
